#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep 22 23:10:52 2019

@author: earllee1
"""


### 라이브러리
import os, sys
import pandas as pd
from multiprocessing import Pool
import glob

### 데이터 불러오기
path = os.getcwd()

rawPath = './100_rawData'
fileNames = os.path.join(rawPath, "*.csv")

# csv 파일 불러와서 해당 변수명으로 저장
for fname in glob.glob(fileNames):
    varName = fname.replace(os.path.join(rawPath,""),"").replace(".csv","")
    tmp = varName + " = pd.read_csv(fname, encoding = 'utf-8', engine = 'python')"
    exec(tmp)
    print(tmp)


